builds:
  - main: ./protoc-gen-graphql/main.go
    id: protoc-gen-graphql
    binary: protoc-gen-graphql
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    format: binary
    replacements:
      amd64: x86_64
dist: _output
