// Code generated by proroc-gen-graphql, DO NOT EDIT.
package empty

import (
	"github.com/graphql-go/graphql"
)

var (
	gql__type_Empty  *graphql.Object      // message Empty in google/protobuf/empty/empty.proto
	gql__input_Empty *graphql.InputObject // message Empty in google/protobuf/empty/empty.proto
)

func Gql__type_Empty() *graphql.Object {
	if gql__type_Empty == nil {
		gql__type_Empty = graphql.NewObject(graphql.ObjectConfig{
			Name: "Empty_Type_Empty",
			Fields: graphql.Fields{
				"_": &graphql.Field{
					Type: graphql.Boolean,
				},
			},
		})
	}
	return gql__type_Empty
}

func Gql__input_Empty() *graphql.InputObject {
	if gql__input_Empty == nil {
		gql__input_Empty = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Empty_Input_Empty",
			Fields: graphql.InputObjectConfigFieldMap{
				"_": &graphql.InputObjectFieldConfig{
					Type: graphql.Boolean,
				},
			},
		})
	}
	return gql__input_Empty
}
