// Code generated by proroc-gen-graphql, DO NOT EDIT.
package timestamp

import (
	"github.com/graphql-go/graphql"
)

var (
	gql__type_Timestamp  *graphql.Object      // message Timestamp in google/protobuf/timestamp/timestamp.proto
	gql__input_Timestamp *graphql.InputObject // message Timestamp in google/protobuf/timestamp/timestamp.proto
)

func Gql__type_Timestamp() *graphql.Object {
	if gql__type_Timestamp == nil {
		gql__type_Timestamp = graphql.NewObject(graphql.ObjectConfig{
			Name: "Timestamp_Type_Timestamp",
			Fields: graphql.Fields{
				"seconds": &graphql.Field{
					Type: graphql.Int,
				},
				"nanos": &graphql.Field{
					Type: graphql.Int,
				},
			},
		})
	}
	return gql__type_Timestamp
}

func Gql__input_Timestamp() *graphql.InputObject {
	if gql__input_Timestamp == nil {
		gql__input_Timestamp = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Timestamp_Input_Timestamp",
			Fields: graphql.InputObjectConfigFieldMap{
				"seconds": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"nanos": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
			},
		})
	}
	return gql__input_Timestamp
}
