name: Pull Request Verification
on:
  pull_request:
  push:
    branches:
      - main

# Kill the workflow if the PR is updated with a new commit
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  buf:
    name: Verify buf
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup buf CLI
        uses: bufbuild/buf-setup-action@v1

      - name: Lint Protobuf sources
        uses: bufbuild/buf-lint-action@v1
        with:
          input: proto

      - name: Build Protobuf sources
        run: buf build
        working-directory: proto

      - name: Breaking Change Detection
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: proto
          against: 'https://github.com/alehechka/grpc-graphql-gateway.git#branch=main,subdir=proto'

  protoc:
    name: Verify examples
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.21.4'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Install protobuf plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      - name: Build example/starwars
        run: make build_all
        working-directory: example/starwars

      - name: Build example/greeter
        run: build_all
        working-directory: example/greeter
